name: oomool
description: "반려어 관리 플랫폼 우물(Oomool) - UT용 프로토타입"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: WantedSans
      fonts:
        - asset: assets/fonts/WantedSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WantedSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WantedSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WantedSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WantedSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WantedSans-Black.ttf
          weight: 900
